In [6]:
import torch 

In [12]:
# Check that MPS is available
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")
else:
    mps_device = torch.device('mps')    

In [15]:
x = torch.ones(5, device=mps_device)
x

tensor([1., 1., 1., 1., 1.], device='mps:0')

In [17]:
y = x * 2
y

tensor([2., 2., 2., 2., 2.], device='mps:0')

In [32]:
import torch 
import math 

dtype = torch.float
device = torch.device("mps") 

x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

y[:30]

tensor([ 8.7423e-08, -3.1430e-03, -6.2863e-03, -9.4292e-03, -1.2572e-02,
        -1.5715e-02, -1.8858e-02, -2.2000e-02, -2.5143e-02, -2.8285e-02,
        -3.1426e-02, -3.4568e-02, -3.7709e-02, -4.0850e-02, -4.3990e-02,
        -4.7130e-02, -5.0269e-02, -5.3408e-02, -5.6547e-02, -5.9684e-02,
        -6.2822e-02, -6.5958e-02, -6.9095e-02, -7.2230e-02, -7.5364e-02,
        -7.8498e-02, -8.1631e-02, -8.4763e-02, -8.7895e-02, -9.1025e-02],
       device='mps:0')

In [42]:
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

lr = 1e-6
for t in range(2000):
    y_pred = a + b * x + c * x ** 2 + d * x ** 3